"use client";

import { useState } from "react";
import {
  FileCheck,
  Loader2,
  AlertCircle,
  Download,
  BarChart3,
  ArrowRight,
  Shield,
  CheckCircle,
} from "lucide-react";
import FileUpload from "@/components/FileUpload";
import ComplianceScore from "@/components/ComplianceScore";
import GapAnalysis from "@/components/GapAnalysis";
import Link from "next/link";
import type { ComplianceResult } from "@/lib/types";

export default function AnalyzePage() {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<ComplianceResult | null>(null);

  const handleFileSelect = async (file: File) => {
    setError(null);
    setLoading(true);

    try {
      let imageBase64: string | undefined;
      let imageMimeType: string | undefined;
      let text: string | undefined;

      if (file.type.startsWith("image/")) {
        const buffer = await file.arrayBuffer();
        imageBase64 = btoa(
          new Uint8Array(buffer).reduce((data, byte) => data + String.fromCharCode(byte), "")
        );
        imageMimeType = file.type;
        text = `Analyze this product image for BIS compliance. File name: ${file.name}`;
      } else {
        text = await file.text();
      }

      const response = await fetch("/api/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text, imageBase64, imageMimeType }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || "Analysis failed");
      }

      setResult(data.data);
    } catch (err: any) {
      setError(err.message || "Failed to analyze product. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleTextInput = async (text: string) => {
    setError(null);
    setLoading(true);

    try {
      const response = await fetch("/api/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || "Analysis failed");
      }

      setResult(data.data);
    } catch (err: any) {
      setError(err.message || "Failed to analyze product. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const downloadReport = () => {
    if (!result) return;

    const report = `
BIS COMPLIANCE ANALYSIS REPORT
================================
Generated: ${new Date().toLocaleString("en-IN")}
Platform: BIS Smart Compliance Portal

PRODUCT INFORMATION
-------------------
Product: ${result.productName}
Category: ${result.productCategory}

COMPLIANCE SCORE: ${result.overallScore}/100
Status: ${result.status.toUpperCase()}

APPLICABLE STANDARDS
--------------------
${result.applicableStandards
  ?.map(
    (s) =>
      `• ${s.isCode} - ${s.title} (Relevance: ${Math.round(s.relevanceScore * 100)}%, Mandatory: ${s.mandatory ? "Yes" : "No"})`
  )
  .join("\n") || "No standards detected"}

COMPLIANCE GAPS
---------------
${result.gaps
  ?.map(
    (g) =>
      `[${g.severity.toUpperCase()}] ${g.standard} - ${g.requirement}\n  Status: ${g.currentStatus}\n  ${g.description}`
  )
  .join("\n\n") || "No gaps found"}

RECOMMENDATIONS
---------------
${result.recommendations
  ?.map(
    (r) =>
      `[${r.priority.toUpperCase()} PRIORITY] ${r.title}\n  Type: ${r.type}\n  ${r.description}\n  Cost: ${r.estimatedCost || "N/A"} | Time: ${r.estimatedTime || "N/A"}`
  )
  .join("\n\n") || "No recommendations"}

---
This report was generated by BIS Smart Compliance Portal - AI Powered.
For official certification, please visit https://www.bis.gov.in
    `.trim();

    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `BIS_Compliance_Report_${result.productName?.replace(/\s+/g, "_") || "Product"}_${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-gradient-to-r from-[#003580] to-[#002a66] text-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
          <div className="flex items-center gap-3 mb-2">
            <div className="bg-white/10 p-2 rounded-lg">
              <FileCheck className="h-6 w-6" />
            </div>
            <h1 className="text-2xl font-bold">AI Product Compliance Analysis</h1>
          </div>
          <p className="text-blue-200 max-w-2xl">
            Upload your product specifications, datasheets, or images. Our AI will detect
            applicable BIS standards, generate a compliance score, and provide actionable recommendations.
          </p>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="grid lg:grid-cols-5 gap-8">
          {/* Left Panel - Upload */}
          <div className="lg:col-span-2">
            <div className="bg-white rounded-2xl border border-gray-200 p-6 shadow-sm sticky top-24">
              <FileUpload
                onFileSelect={handleFileSelect}
                onTextInput={handleTextInput}
                loading={loading}
                label="Upload Product Information"
                description="Drop product specs, datasheets, or product images"
              />

              {/* Quick Examples */}
              <div className="mt-6 pt-4 border-t border-gray-100">
                <p className="text-xs font-semibold text-gray-500 mb-3 uppercase tracking-wider">
                  Try an example
                </p>
                <div className="space-y-2">
                  {[
                    "Electric kettle, 1500W, stainless steel body, 1.5L capacity, BEE rated",
                    "PVC pipes 4 inch diameter for drinking water supply, HDPE material",
                    "LED bulb 12W, 1200 lumens, B22 base, for household use",
                  ].map((example) => (
                    <button
                      key={example}
                      onClick={() => handleTextInput(example)}
                      disabled={loading}
                      className="w-full text-left px-3 py-2 rounded-lg text-xs text-gray-600 bg-gray-50 hover:bg-blue-50 hover:text-[#003580] transition-colors disabled:opacity-50"
                    >
                      &quot;{example}&quot;
                    </button>
                  ))}
                </div>
              </div>
            </div>
          </div>

          {/* Right Panel - Results */}
          <div className="lg:col-span-3">
            {/* Loading State */}
            {loading && (
              <div className="bg-white rounded-2xl border border-gray-200 p-12 text-center shadow-sm">
                <Loader2 className="h-12 w-12 text-[#003580] animate-spin mx-auto mb-4" />
                <h3 className="text-lg font-bold text-gray-900 mb-2">
                  Analyzing Your Product...
                </h3>
                <p className="text-sm text-gray-500">
                  Our AI is matching your product against 20,000+ BIS standards
                </p>
                <div className="mt-6 space-y-2 max-w-xs mx-auto">
                  {["Detecting product category", "Matching IS codes", "Evaluating compliance", "Generating recommendations"].map(
                    (step, i) => (
                      <div key={step} className="flex items-center gap-2 text-xs text-gray-400">
                        <div className="w-1.5 h-1.5 rounded-full bg-[#003580] animate-pulse" style={{ animationDelay: `${i * 0.3}s` }} />
                        {step}
                      </div>
                    )
                  )}
                </div>
              </div>
            )}

            {/* Error State */}
            {error && !loading && (
              <div className="bg-red-50 border border-red-200 rounded-2xl p-6">
                <div className="flex items-start gap-3">
                  <AlertCircle className="h-5 w-5 text-red-500 mt-0.5" />
                  <div>
                    <h3 className="font-semibold text-red-800">Analysis Error</h3>
                    <p className="text-sm text-red-600 mt-1">{error}</p>
                    <button
                      onClick={() => setError(null)}
                      className="mt-3 text-sm text-red-700 underline hover:no-underline"
                    >
                      Dismiss
                    </button>
                  </div>
                </div>
              </div>
            )}

            {/* Results */}
            {result && !loading && (
              <div className="space-y-6 animate-fade-in-up">
                {/* Actions bar */}
                <div className="flex items-center justify-between">
                  <h2 className="text-lg font-bold text-gray-900">Analysis Results</h2>
                  <div className="flex gap-2">
                    <button
                      onClick={downloadReport}
                      className="flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-medium bg-white border border-gray-200 text-gray-700 hover:bg-gray-50 transition-colors"
                    >
                      <Download className="h-4 w-4" />
                      Download Report
                    </button>
                    <Link
                      href="/simulate"
                      className="flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-medium bg-[#003580] text-white hover:bg-[#002a66] transition-colors"
                    >
                      <BarChart3 className="h-4 w-4" />
                      Run Simulation
                    </Link>
                  </div>
                </div>

                {/* Score */}
                <ComplianceScore
                  score={result.overallScore}
                  status={result.status}
                  productName={result.productName}
                />

                {/* Applicable Standards */}
                {result.applicableStandards && result.applicableStandards.length > 0 && (
                  <div className="bg-white rounded-2xl border border-gray-200 p-6">
                    <h3 className="text-lg font-bold text-gray-900 mb-4">
                      Applicable BIS Standards
                    </h3>
                    <div className="space-y-3">
                      {result.applicableStandards.map((std) => (
                        <div
                          key={std.isCode}
                          className="flex items-center justify-between p-3 rounded-xl bg-gray-50 hover:bg-blue-50 transition-colors"
                        >
                          <div className="flex items-center gap-3">
                            <Shield className="h-5 w-5 text-[#003580]" />
                            <div>
                              <span className="text-sm font-mono font-bold text-[#003580]">
                                {std.isCode}
                              </span>
                              <p className="text-xs text-gray-600">{std.title}</p>
                            </div>
                          </div>
                          <div className="flex items-center gap-3">
                            <div className="text-right">
                              <div className="text-xs text-gray-500">
                                Relevance: {Math.round(std.relevanceScore * 100)}%
                              </div>
                            </div>
                            {std.mandatory && (
                              <span className="px-2 py-0.5 rounded text-xs font-semibold bg-red-100 text-red-700">
                                Mandatory
                              </span>
                            )}
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Gaps & Recommendations */}
                {((result.gaps && result.gaps.length > 0) ||
                  (result.recommendations && result.recommendations.length > 0)) && (
                  <GapAnalysis
                    gaps={result.gaps || []}
                    recommendations={result.recommendations || []}
                  />
                )}
              </div>
            )}

            {/* Empty State */}
            {!result && !loading && !error && (
              <div className="bg-white rounded-2xl border border-gray-200 p-12 text-center shadow-sm">
                <div className="bg-blue-50 p-4 rounded-full w-fit mx-auto mb-4">
                  <FileCheck className="h-10 w-10 text-[#003580]" />
                </div>
                <h3 className="text-lg font-bold text-gray-900 mb-2">
                  Upload Product Information
                </h3>
                <p className="text-sm text-gray-500 max-w-md mx-auto mb-6">
                  Upload your product specs, datasheets, images, or describe your product.
                  Our AI will instantly analyze it against BIS standards.
                </p>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 max-w-lg mx-auto">
                  {[
                    { icon: "📋", label: "Compliance Score" },
                    { icon: "🔍", label: "Gap Analysis" },
                    { icon: "💡", label: "Recommendations" },
                  ].map((item) => (
                    <div key={item.label} className="bg-gray-50 rounded-lg p-3">
                      <div className="text-2xl mb-1">{item.icon}</div>
                      <div className="text-xs font-medium text-gray-600">{item.label}</div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
